<a href="https://colab.research.google.com/github/tjsiledar/Machine-Learning/blob/master/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
def featureNormalize(X):
  
  m,n = X.shape
  
  mu = np.mean(X, axis=0).reshape(1,n)
  sigma = np.std(X, axis=0).reshape(1,n)
  
  X_norm = (X-mu)/sigma
  
  return X_norm, mu, sigma

In [0]:
def initialize(X):
  
  m = X.shape[0]
  temp = np.ones((m,1))
  X = np.insert(X, [0], temp, axis=1)  #adding the column of ones to the X matrix
  
  return X

In [0]:
def computeCost(theta,X,y):
  
  (m,n) = X.shape
  
  theta = theta.reshape(n,1)
  
  a = np.dot(X,theta)
  error = np.power((a-y),2)
  cost = np.sum(error)/(2*m)
  
  grad = (1/m)*np.dot(X.T,a-y)
  
  return cost, grad

In [0]:
import scipy.optimize as opt

In [0]:
def optimizeTheta(initial_theta, X, y):
  
  final_theta, a, b = opt.fmin_tnc(func=computeCost, x0=initial_theta, args=(X,y))
  
  return final_theta

In [0]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
from google.colab import files
files.upload()

Saving ex1data1.txt to ex1data1.txt
Saving ex1data2.txt to ex1data2.txt


{'ex1data1.txt': b'6.1101,17.592\n5.5277,9.1302\n8.5186,13.662\n7.0032,11.854\n5.8598,6.8233\n8.3829,11.886\n7.4764,4.3483\n8.5781,12\n6.4862,6.5987\n5.0546,3.8166\n5.7107,3.2522\n14.164,15.505\n5.734,3.1551\n8.4084,7.2258\n5.6407,0.71618\n5.3794,3.5129\n6.3654,5.3048\n5.1301,0.56077\n6.4296,3.6518\n7.0708,5.3893\n6.1891,3.1386\n20.27,21.767\n5.4901,4.263\n6.3261,5.1875\n5.5649,3.0825\n18.945,22.638\n12.828,13.501\n10.957,7.0467\n13.176,14.692\n22.203,24.147\n5.2524,-1.22\n6.5894,5.9966\n9.2482,12.134\n5.8918,1.8495\n8.2111,6.5426\n7.9334,4.5623\n8.0959,4.1164\n5.6063,3.3928\n12.836,10.117\n6.3534,5.4974\n5.4069,0.55657\n6.8825,3.9115\n11.708,5.3854\n5.7737,2.4406\n7.8247,6.7318\n7.0931,1.0463\n5.0702,5.1337\n5.8014,1.844\n11.7,8.0043\n5.5416,1.0179\n7.5402,6.7504\n5.3077,1.8396\n7.4239,4.2885\n7.6031,4.9981\n6.3328,1.4233\n6.3589,-1.4211\n6.2742,2.4756\n5.6397,4.6042\n9.3102,3.9624\n9.4536,5.4141\n8.8254,5.1694\n5.1793,-0.74279\n21.279,17.929\n14.908,12.054\n18.959,17.054\n7.2182,4.88

In [0]:
data = pd.read_csv("ex1data2.txt", names = ['Size', 'Bedrooms', 'Price'])

In [74]:
data.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [0]:
X = data.values[:,0:2]

In [76]:
X.shape

(47, 2)

In [0]:
y = data.values[:,-1].reshape(47,1)

In [78]:
y.shape

(47, 1)

In [0]:
X, mu, sigma = featureNormalize(X)

In [80]:
X

array([[ 1.31415422e-01, -2.26093368e-01],
       [-5.09640698e-01, -2.26093368e-01],
       [ 5.07908699e-01, -2.26093368e-01],
       [-7.43677059e-01, -1.55439190e+00],
       [ 1.27107075e+00,  1.10220517e+00],
       [-1.99450507e-02,  1.10220517e+00],
       [-5.93588523e-01, -2.26093368e-01],
       [-7.29685755e-01, -2.26093368e-01],
       [-7.89466782e-01, -2.26093368e-01],
       [-6.44465993e-01, -2.26093368e-01],
       [-7.71822042e-02,  1.10220517e+00],
       [-8.65999486e-04, -2.26093368e-01],
       [-1.40779041e-01, -2.26093368e-01],
       [ 3.15099326e+00,  2.43050370e+00],
       [-9.31923697e-01, -2.26093368e-01],
       [ 3.80715024e-01,  1.10220517e+00],
       [-8.65782986e-01, -1.55439190e+00],
       [-9.72625673e-01, -2.26093368e-01],
       [ 7.73743478e-01,  1.10220517e+00],
       [ 1.31050078e+00,  1.10220517e+00],
       [-2.97227261e-01, -2.26093368e-01],
       [-1.43322915e-01, -1.55439190e+00],
       [-5.04552951e-01, -2.26093368e-01],
       [-4.

In [81]:
mu.shape

(1, 2)

In [0]:
X = initialize(X)

In [83]:
X.shape

(47, 3)

In [84]:
y

array([[399900],
       [329900],
       [369000],
       [232000],
       [539900],
       [299900],
       [314900],
       [198999],
       [212000],
       [242500],
       [239999],
       [347000],
       [329999],
       [699900],
       [259900],
       [449900],
       [299900],
       [199900],
       [499998],
       [599000],
       [252900],
       [255000],
       [242900],
       [259900],
       [573900],
       [249900],
       [464500],
       [469000],
       [475000],
       [299900],
       [349900],
       [169900],
       [314900],
       [579900],
       [285900],
       [249900],
       [229900],
       [345000],
       [549000],
       [287000],
       [368500],
       [329900],
       [314000],
       [299000],
       [179900],
       [299900],
       [239500]])

In [0]:
initial_theta = np.zeros(3)

In [86]:
initial_theta.shape

(3,)

In [87]:
computeCost(initial_theta,X,y)

(65591548106.45744, array([[-340412.65957447],
        [-105764.13349282],
        [ -54708.82175587]]))

In [0]:
final_theta = optimizeTheta(initial_theta,X,y)

In [89]:
final_theta

array([340412.66004781, 109447.79655954,  -6578.35468326])

In [0]:
a = np.array([1650,3])

In [91]:
a

array([1650,    3])

In [0]:
a = (a-mu)/sigma

In [93]:
a

array([[-0.44604386, -0.22609337]])

In [0]:
 a = np.insert(a, [0], 1, axis=1)

In [95]:
a

array([[ 1.        , -0.44604386, -0.22609337]])

In [97]:
np.dot(a,final_theta)


array([293081.4647295])